name: 🚀 Deploy website on push

on:
    push:
        branches:
            - main

jobs:
    web-deploy:
        name: 🎉 Deploy
        runs-on: ubuntu-latest

        steps:
            - name: 🚚 Get latest code
              uses: actions/checkout@v4

            - name: 📂 Sync files
              uses: SamKirkland/FTP-Deploy-Action@4.3.0
              with:
                  server: ${{ secrets.FTP_SERVER }}
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  server-dir: /public_html/studio-val/wp-content/themes/studio-val/
                  exclude: |
                      **/.git*
                      **/.git*/**
                      **/node_modules/**
                      **/.vscode/**
